/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module
import QuadraticAlgebras

/-!
# README negative-five example

The discriminant and class number of the field generated by a square root
of minus five.

This named private client is the corresponding README Lean block. It adds no public API.
-/

private theorem negativeFiveDiscriminantAndClassNumber :
    NumberField.discr QuadraticAlgebra.SqrtNegFiveField = -20 ∧
      NumberField.classNumber QuadraticAlgebra.SqrtNegFiveField = 2 :=
  ⟨QuadraticAlgebra.discr_sqrtNegFiveField,
    QuadraticAlgebra.classNumber_sqrtNegFiveField⟩
